### ISSUE TITLE
Try using unsafe/pointers to exactly copy the original C code?

### ISSUE THREAD

**Issue by markashleybell** [markashleybell/MAB.DotIgnore#11]
More of an exercise than an actual necessity, but I'd be interested to see if a) it helps performance (although that's not really an issue anyway) and b) if it sorts out the remaining failing tests

**Comment by markashleybell** [comment]
Does `Span<T>` help us with this? See here: http://adamsitnik.com/Span/

**Comment by atifaziz** [comment]
> b) if it sorts out the remaining failing tests

```
$ dotnet test MAB.DotIgnore.Test
Build started, please wait...
Build completed.

Test run for A:\MAB.DotIgnore\MAB.DotIgnore.Test\bin\Debug\netcoreapp2.0\MAB.DotIgnore.Test.dll(.NETCoreApp,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 15.8.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

Total tests: 82. Passed: 82. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 4.7129 Seconds
```

Are there any failing tests still?

**Comment by atifaziz** [comment]
> original C code

Incidentally, which/where is the original C code?

**Comment by atifaziz** [comment]
>> original C code
>
> Incidentally, which/where is the original C code? Would that be [`wildmatch.c` from Git](https://github.com/git/git/blob/55d3426929d4d8c3dec402cabe6fb1bf27d6abad/wildmatch.c)?

Never mind. [I found it my answer](https://github.com/markashleybell/MAB.DotIgnore/tree/5130eee3fcff2c264a2868f0d0fd2b186f72713b/MAB.DotIgnore.Test/test_content/git-wildmatch). 😄

**Comment by markashleybell** [comment]
Sorry, this issue was only really ever meant for me, so I wasn't very clear...

The original C function I'm testing against (copied from the [git source](https://github.com/git/git/blob/53f9a3e157dbbc901a02ac2c73346d375e24978c/wildmatch.c)) is [here](https://github.com/markashleybell/MAB.DotIgnore/tree/master/MAB.DotIgnore.Test/test_content/git-wildmatch). 

The failing tests I'm talking about are the `wildmatch` tests [here](https://github.com/markashleybell/MAB.DotIgnore/blob/master/MAB.DotIgnore.Test/test_content/tests.txt) (also copied from the git repo). 

I [commented some of these out](https://github.com/markashleybell/MAB.DotIgnore/commit/146667d1f22c2f7c184e617b2747e2d93d5e7185) as my code fails them, but they are fairly uncommonly-used patterns so I made the decision not to support them at the time.

Two years later, I've still not encountered a case where this has been a problem, so I'm inclined to leave it. However, pull requests are gratefully accepted!

**Comment by atifaziz** [comment]
I think it's possible to maintain 99% of the original C code without using pointers or `Span<T>` and it will help performance (especially with respect to GC and fewer allocations), as well as take care of any failing tests. I'll try and share the results of my spike. Nevertheless, one item of concern is that the Git source is published under the GPL license, which means that anything derived from it will need to be released under the same license and terms, including this library. [At present, it re-publishes under the MIT License](https://github.com/markashleybell/MAB.DotIgnore/blob/a3965b131689f80dad8bf7e63d12d17f4cda7625/LICENSE.md), which technically violates the terms of the GPL. 😕

**Comment by atifaziz** [comment]
I think 1 is the only viable and _fair_ option. 3 and 4 have been done by others so wonder what would be the distinctive offering if this library were to do the same. A fifth option is to have an out-of-process service that's GPL-licensed with a non-GPL library wrapper but I think we can agree that would be a clear winner in the overkill category.

> …the original `wildmatch` implementation was a replacement for `fnmatch`, and actually came from [rsync](https://rsync.samba.org/)…

Interesting but `rsync` is also distributed under the GPL license so it doesn't help the situation.

> There is a BSD-licensed C implementation [here](https://github.com/davvid/wildmatch), …

This could be a call but what attracted me to this project was that it was based on the Git implementation and tests.

**Comment by atifaziz** [comment]
Me [earlier](https://github.com/markashleybell/MAB.DotIgnore/issues/11#issuecomment-433456636):

> I'll try and share the results of my spike.

So I've [published my spike](https://github.com/atifaziz/WildWildMatch), for whatever it's worth. 💰 

See [`dowild` in `GitWildMatch`](https://github.com/atifaziz/WildWildMatch/blob/a6302c09ebbb72746d5463ed50b8db8bd3cf2416/src/GitWildMatch.cs#L181-L410). The code is 99% identical to the original source from Git (minus the whitespace changes). [As the `README` states](https://github.com/atifaziz/WildWildMatch/blob/a6302c09ebbb72746d5463ed50b8db8bd3cf2416/README.md), I used every dirty trick offered by C# to create types that can emulate the behaviour of the original C types. All [tests](https://github.com/atifaziz/WildWildMatch/blob/a6302c09ebbb72746d5463ed50b8db8bd3cf2416/tests/tests.txt) pass, including [those that were commented out here](https://github.com/markashleybell/MAB.DotIgnore/commit/146667d1f22c2f7c184e617b2747e2d93d5e7185)! 🙌I have not measured the performance improvements but I reckon there are many since there is no added GC pressure during the execution of the algorithm. The [only call to `String.Substring`](https://github.com/atifaziz/WildWildMatch/blob/a6302c09ebbb72746d5463ed50b8db8bd3cf2416/src/GitWildMatch.cs#L118) is entirely adjacent.

License issues pending, I'm happy to collaborate to combine our efforts for the benefit of the community.

**Comment by markashleybell** [comment]
Thanks, I do appreciate your feedback and help. That spike looks very interesting, nice work!

Everything you said regarding the licensing options makes sense; however, I am currently looking into a different, custom implementation anyway. While I'm all for the GPL, there are going to be use cases (not least my own, in future) which it will complicate dramatically.

I agree that it's a great selling point that this passes the same tests as the git implementation, but I'm not sure many people (other than us 😉) will care about how it actually achieves those results.

Another thing which has come out of this is that the reference git tests in this project are actually quite outdated, so it's possible that the existing library doesn't quite perform in the same way as the current git version anyway. 

If I can't come up with anything which matches the existing performance and results, then incorporating your code and re-licensing under the GPL would be my next step.

Anyway, I will hopefully get some time to work it out this weekend—I'll keep you posted!

**Comment by atifaziz** [comment]
> but I'm not sure many people (other than us 😉) will care about how it actually achieves those results.

To be honest, I shouldn't be caring either because that's the whole point of passing tests but I found it easier going to bed using a library that was based off the original code. That aside, I felt if the code can be kept 99% identical at the source level then sync'ing up with any changes would take 5 minutes. As a side-effect, there's the performance benefit from having zero-allocations.

> Another thing which has come out of this is that the reference git tests in this project are actually quite outdated, so it's possible that the existing library doesn't quite perform in the same way as the current git version anyway.

Ouch! On [my spike](https://github.com/atifaziz/WildWildMatch), I'm seeing this coverage:

| Module        | Line   | Branch | Method |
|---------------|--------|--------|--------|
| WildWildMatch | 90.2%  | 82.4%  | 83.1%  |

> 📎 [`WildWildMatchCoverageReport.zip`](https://github.com/markashleybell/MAB.DotIgnore/files/2539460/WildWildMatchCoverageReport.zip)

There are certainly some missed code paths.

> then incorporating your code and re-licensing under the GPL would be my next step.

:+1: Happy to submit a PR if it helps.

**Comment by markashleybell** [comment]
I'm closing this one, because the regex-based version is working well enough and this was more of an exercise anyway.
